CREATE TABLE IF NOT EXISTS "Tbl_Cola" (
    "id"            BIGSERIAL PRIMARY KEY,
    "nombre"        VARCHAR(100) NOT NULL,
    "activo"        BOOLEAN NOT NULL DEFAULT TRUE,
    "fechaRegistro" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "fechaEdicion"  TIMESTAMP WITH TIME ZONE NULL
);
