<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>7.3</LangVersion>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<AnalyzerLanguage>CS</AnalyzerLanguage>
		<DevelopmentDependency>true</DevelopmentDependency>
		
		<!-- Configuración para .NET Standard 2.0 -->
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<AssemblyVersion>1.0.0.5</AssemblyVersion>
		<FileVersion>1.0.0.5</FileVersion>
		
		<!-- Suprimir warnings específicos para analizadores -->
		<NoWarn>$(NoWarn);NU5128;CS8618;CS8625;RS2000;RS2001;RS2005;RS1030;RS1032;RS1037;RS2008</NoWarn>
		
		<!-- Desactivar análisis en este proyecto -->
		<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
		<EnableNETAnalyzers>false</EnableNETAnalyzers>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.11.0" />
	</ItemGroup>

</Project>