<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Japdeva.APIMovil.Estandar\Japdeva.APIMovil.Estandar.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Middlewares\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="log4net" Version="3.3.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="8.0.0" />
	  <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.17.0" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
	  <PackageReference Include="Ocelot" Version="24.1.0" />
	  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
	</ItemGroup>

</Project>
