<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Japdeva.APIMovil.Estandar\Japdeva.APIMovil.Estandar.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Middlewares\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="log4net" Version="3.2.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="8.0.0" />
	  <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.2" />
	  <PackageReference Include="Ocelot" Version="24.0.1" />
	  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
	</ItemGroup>

</Project>
